import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import { BrowserRouter } from "react-router-dom";
import reportWebVitals from "./reportWebVitals";
import axios from "axios";

const root = ReactDOM.createRoot(document.getElementById("root"));

axios.defaults.baseURL = process.env.REACT_APP_API_URL;
axios.defaults.headers.common['Authorization'] = 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxV2pTc0pfU2ZkUU5FaWtCdU82alo4bXNVN0JERXFTZkRmTWJVSmpHSk5RIn0.eyJleHAiOjE2NTI1MDg0ODEsImlhdCI6MTY1MjUwNDg4MSwianRpIjoiMGU1ZWU2ZGEtZjc1Yi00M2VhLWJjOWMtZjJjMTg0MTQ5MDRlIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9wbXAtcmVhbG0iLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMjBjMTlmMDQtMDViYy00YzU5LWIzMmUtOTJlOTA5N2M3ZDNmIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicG1wLWNsaWVudCIsInNlc3Npb25fc3RhdGUiOiI5MGU5ZDlkOC1iMmM3LTQyZTEtOTY5My1jMTE1YTQ0M2VkZjkiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vbG9jYWxob3N0OjgwODEiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtcG1wLXJlYWxtIiwib2ZmbGluZV9hY2Nlc3MiLCJST0xFX0FETUlOIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiI5MGU5ZDlkOC1iMmM3LTQyZTEtOTY5My1jMTE1YTQ0M2VkZjkiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJSb21hIE11cmF6aWsiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbjFAZ21haWwuY29tIiwiZ2l2ZW5fbmFtZSI6IlJvbWEiLCJmYW1pbHlfbmFtZSI6Ik11cmF6aWsiLCJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20ifQ.Efr4Z7NfjIIamAsb5u0wFYpHYfL6OXCWpBIyiKEvMJojDcLlNknsnF-WxaM_ZOQb12WE05JbBZwO2HkHI_J-XrPAHJYePlH2_Xv0z88rv4i16a89iUweJagNDBQQWosnDhHKBXHy_hhtV5F_-pqtoCKAv7eW8mt0SyZw24v6P0-pZ3hAPTYYscR3q9Tavo-vRPqCgDqU5KzaYEHropRP6jf1auuzRc-vO_YO2JHxqH2L_16436sYbV-kCtCFWxjiWrDKg-xW0Flv-9mW8dYTsbZkStN3XgynWnzc_62T3k3QzgTVt-18LL-Z5OaLhMB4Hpk13oSJxUnn33qHr7jTbg';

root.render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
