import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import { BrowserRouter } from "react-router-dom";
import reportWebVitals from "./reportWebVitals";
import axios from "axios";

const root = ReactDOM.createRoot(document.getElementById("root"));

axios.defaults.baseURL = process.env.REACT_APP_API_URL;
axios.defaults.headers.common['Authorization'] = 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxV2pTc0pfU2ZkUU5FaWtCdU82alo4bXNVN0JERXFTZkRmTWJVSmpHSk5RIn0.eyJleHAiOjE2NTI1NDQ5MjMsImlhdCI6MTY1MjUwODkyMywianRpIjoiODNkZWI5ZmItNDM0My00NTUxLTkxYWQtZTNkOTA2MjRkOTc2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9wbXAtcmVhbG0iLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiYzk2ZmZjMWEtNGMxMi00YWZkLWEzNmQtZDM2Njk3NmVlNGU0IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicG1wLWNsaWVudCIsInNlc3Npb25fc3RhdGUiOiIwNmU2ODYyMS04MmJmLTQ5NDctYmJkMS0xYTkwYzljYzVhNTkiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vbG9jYWxob3N0OjgwODEiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtcG1wLXJlYWxtIiwib2ZmbGluZV9hY2Nlc3MiLCJST0xFX0FETUlOIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiIwNmU2ODYyMS04MmJmLTQ5NDctYmJkMS0xYTkwYzljYzVhNTkiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJEb3lsZSBDaGFtcGxpbiIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluMUBnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiRG95bGUiLCJmYW1pbHlfbmFtZSI6IkNoYW1wbGluIiwiZW1haWwiOiJhZG1pbjFAZ21haWwuY29tIn0.fhmJp7D10Y49nGdo7bfOLHgH-J_KaaNC-3vzLLOa_kGk6zQKcCp63MqdXvQKNeR2kxx5wxX2fJ7a5AN1WhkMyOjlEiEcQI3HRzrd-BtPp3K0cgsTpH0_Px5UrQ3Uvj--2-ZgkuRRIpdgDRbc0O4BtMIBj-KucMx-era7cCJ6J4_jpPsr5C27M2zHD1lwbiTZbyvxd1nlbeQOTd6Y3t-_Uy-oX3lhravkeNrzx43qGlT1851GPssw3ntwLDl28KrZqSga4fY1toB40DkiFU4cCrORAYfU3zzAZDOugzQX26YEQRhP0lh8Q7QRfBawm5hWCvX1a1THzBPr_7Mg9aXQQg';

root.render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
