import styled from "styled-components";

export const ContainerFormProperties = styled.div`
  background-color: #ffffff;
  width: 800px;
  height: 600px;
  margin: 7em auto;
  border-radius: 1.5em;
  box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);
  align: center;
`;
export const ContainerInputProperties = styled.input`
  width: 46%;
  color: rgb(38, 50, 56);
  font-weight: 700;
  font-size: 14px;
  letter-spacing: 1px;
  background: rgba(136, 126, 126, 0.04);
  padding: 10px 20px;
  border: none;
  border-radius: 20px;
  outline: none;
  box-sizing: border-box;
  border: 2px solid rgba(0, 0, 0, 0.02);
  margin-bottom: 35px;
  margin-left: 1%;
  text-align: center;
  font-family: "Ubuntu", sans-serif;
`;
export const ContainerSelectStates = styled.select`
  width: 46%;
  color: rgb(38, 50, 56);
  font-weight: 700;
  font-size: 14px;
  letter-spacing: 1px;
  background: rgba(136, 126, 126, 0.04);
  padding: 10px 20px;
  border: none;
  border-radius: 20px;
  outline: none;
  box-sizing: border-box;
  border: 2px solid rgba(0, 0, 0, 0.02);
  margin-bottom: 35px;
  margin-left: 1%;
  text-align: center;
  font-family: "Ubuntu", sans-serif;
`;
export const ContainerInputShorts = styled.input`
  width: 20%;
  color: rgb(38, 50, 56);
  font-weight: 700;
  font-size: 14px;
  letter-spacing: 1px;
  background: rgba(136, 126, 126, 0.04);
  padding: 10px 20px;
  border: none;
  border-radius: 20px;
  outline: none;
  box-sizing: border-box;
  border: 2px solid rgba(0, 0, 0, 0.02);
  margin-bottom: 35px;
  margin-left: 1%;
  text-align: center;
  font-family: "Ubuntu", sans-serif;
`;
export const ContainerSelectTypes = styled.select`
  width: 30%;
  color: rgb(38, 50, 56);
  font-weight: 700;
  font-size: 14px;
  letter-spacing: 1px;
  background: rgba(136, 126, 126, 0.04);
  padding: 10px 20px;
  border: none;
  border-radius: 20px;
  outline: none;
  box-sizing: border-box;
  border: 2px solid rgba(0, 0, 0, 0.02);
  margin-bottom: 35px;
  margin-left: 1%;
  text-align: center;
  font-family: "Ubuntu", sans-serif;
`;
